# How to install R and R Studio

## Why R
Biologists use a variety of tools and in recent years, the use of computers has become widespread. Many different softwares are used by biologists including Microsoft Office, R, Python, and ArcGIS. First year biology, will introduce you to using R to visualize data, although we note that many of the same end results could be generated using different software. Our choice of R is for the following reasons:

1. R programming is a valued skill: citation.

1. Reproducibility:

1. Accessibility: `R` is free.

1. No limits: while it is possible to need data visualization options or statistical analysis that are unavailable in `Microsoft Excel` this is rarely a problem in `R`: there is an `R` package for anything, from [serious](https://rviews.rstudio.com/2017/10/09/population-modeling-in-r/) to [fun](https://www.r-bloggers.com/useless-but-fun-r-packages/)).


## R
`R` can be installed from https://www.r-project.org/. If you have problems with installing `R` this same website provides advice on how to seek support.

## RStudio
`R` is a scripting language. `R Studio` is a graphical user interface (GUI) that facilitates `R` coding by providing buttons and menus to provide options for some commonly used commands. 
